import type { Metadata } from "next";

import { GeistMono } from "geist/font/mono";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { AuthenticatedCopilotKit } from "@/components/AuthenticatedCopilotKit";

// 使用系统字体替代 Google Fonts，避免构建时网络问题
const manrope = {
  variable: "--font-manrope",
};

export const metadata: Metadata = {
  title: "AG-UI Canvas | CopilotKit with LangGraph Python",
  description: "Generated by CopilotKit with LangGraph Python",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${GeistMono.variable}`}>
      <body className="subpixel-antialiased">
        <AuthProvider>
          <AuthenticatedCopilotKit>
            {children}
          </AuthenticatedCopilotKit>
        </AuthProvider>
      </body>
    </html>
  );
}
