import type { Metadata } from "next";

import { GeistMono } from "geist/font/mono";
import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

// 使用系统字体替代 Google Fonts，避免构建时网络问题
const manrope = {
  variable: "--font-manrope",
};

export const metadata: Metadata = {
  title: "AG-UI Canvas | CopilotKit with LangGraph Python",
  description: "Generated by CopilotKit with LangGraph Python",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${GeistMono.variable}`}>
      <body className="subpixel-antialiased">
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          agent="sample_agent"
          showDevConsole={false}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
