services:
  # 前端服务 (Next.js) - 开发模式
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_AGENT_URL=http://backend:8123
      - LANGGRAPH_URL=http://backend:8123
      - COPILOT_CLOUD_PUBLIC_API_KEY=${COPILOT_CLOUD_PUBLIC_API_KEY:-}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/next.config.ts
        - action: rebuild
          path: ./frontend/tailwind.config.js
        - action: rebuild
          path: ./frontend/tsconfig.json

  # 后端服务 (Python LangGraph) - 开发模式
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8123:8123"
    environment:
      - PYTHONPATH=/app/agent
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-langgraph-canvas}
      # Azure OpenAI 配置
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-gpt-4o-mini}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync
          path: ./backend/agent
          target: /app/agent
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile.backend

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  python_cache:
